export const ACTION = {
   LOADING_GET_DRIVER_DATA: "LOADING_GET_DRIVER_DATA",
   GET_DRIVER_DATA: " GET_DRIVER_DATA",
   SEARCH_DRIVER: "SEARCH_DRIVER",
   PAGINATE_PREV: "PAGINATE_PREV",
   PAGINATE_NEXT: "PAGINATE_NEXT",
};
